spring.application.name=authservice

# --- Database Config ---
spring.datasource.url=jdbc:mysql://localhost:3306/auth_database
spring.datasource.username=root
spring.datasource.password=Dhami@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# --- Email (SMTP) Config ---
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.smtp.starttls.enable=

# JWT Configuration
jwt.expiration.hours=24
jwt.secret=hA7DnFf8vVfC3T1eZ2k7UqLbVtJ9qYgW0fP+9r5cOvQ=

# Redis config
spring.redis.host=
spring.redis.port=

